<a href="https://colab.research.google.com/github/MonitSharma/Numerical-Linear-Algebra/blob/main/Scalars%2C_Vectors%2C_Matrices_and_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import numpy

import numpy as np

Author: [Monit Sharma](https://github.com/MonitSharma),
        LinkedIn: [Monit Sharma](https://www.linkedin.com/in/monitsharma/),
        Twitter: [@MonitSharma1729](https://twitter.com/MonitSharma1729)

# Introduction

This first chapter is quite light and concerns the basic elements used in linear algebra and their definitions. It also introduces important functions in Python/Numpy that we will use all along this series. It will explain how to create and use vectors and matrices through examples.

# Scalars, Vectors, Matrices and Tensors

Let's start with some basic definition

![](https://github.com/akhilvasvani/Linear-Algebra-Basics/blob/master/Chapters/2.01%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/scalar-vector-matrix-tensor.png)




*Difference between a scalar, a vector , a matrix and a tensor*

<li> A scalar is a single number or a mtrix with single entry.

<li> A vector is a 1-d array of numbers. Another way to think of vectors is identifying points in space with each element giving the coordinate along a different axis.

$$ {x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}$$


<li> A matrix is a 2-D array where each element is identified by two indices (ROW then COLUMN).

$$ {A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix} $$


<li> A tensor is a $n$-dimensional array with $n>2$


-------

1. scalars are written in lowercase and italics. For instance: $n$

2. vectors are written in lowercase, italics and bold type. For instance: $x$

3. matrices are written in uppercase, italics and bold. For instance: $X$ 


## Example 1:

### Create a vector with Python and Numpy

*Coding tip* : Unlike the `matrix()` function which necessarily creates $2$-dimensional matrices, you can create $n$-dimensional arrays with the `array()` function. The main advantage to use `matrix()` is the useful methods (conjugate transpose, inverse...). We will use the `array()` function in this series.



------

We will start by creating a vector. This is just a $1$-dimensional array:

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
x.shape

(4,)

## Example 2:

### Create a $3 \times 2$ matrix with nested brackets.

The `array()` function can also create $2$ dimensional arrays with nested brackets:

In [3]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### Shape

The shape of an array (that is to say its dimensions) tells you the number of values for each dimension. For a 
$2$-dimensional array it will give you the number of rows and the number of columns. Let's find the shape of our preceding 
$2$-dimensional array `A`. Since `A` is a Numpy array (it was created with the `array()` function) you can access its shape with:


In [4]:
A.shape

(3, 2)

We can see that $A$ has $3$ rows and $2$ columns.

-----

Let's see the shape of our first vector:

In [8]:
x.shape

(4,)

As expected you can see that $x$ has only one dimension. The number corresponds to the length of the array:

In [9]:
len(x)

4

## Transposition

With transposition you can convert a row vector to a column vector and vice versa.

-----

The transpose $A^T$
 of the matrix $A$
 corresponds to the mirrored axes. If the matrix is a square matrix (same number of columns and rows).


 -----

 $$ {A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix} $$



----

$${A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}$$

## Example 3:

### Create a matrix A and transpose it

In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
A.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Checking the dimensions

In [6]:
A.shape

(3, 2)

In [7]:
A_t.shape

(2, 3)

We can see that the number of columns becomes the number of rows with transposition and vice versa.

# Addition

Matrices can be added if they have the same shape:

$$ A + B = C $$

Each cell of $A$ is added to the corresponding cell of $B$:

$$ {A}_{i,j} + {B}_{i,j} = {C}_{i,j}$$

$i$ is the row index and $j$ the column index.

$$ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix} $$


The shape of $A,B$ and $C$ are identical. Let's check that in an example

## Example 4

### Create two matrices A and B and add them

With Numpy you can add matrices just as you would add vectors or scalars.


In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [10]:
# Add matrices A and B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

It is also possible to add a scalar to a matrix. This means adding this scalar to each cell of the matrix.


$$ \alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix} $$

## Example 5

### Add a scalar to a matrix

In [11]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# Exemple: Add 4 to the matrix A
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Broadcasting

Numpy can handle operations on arrays of different shapes. The smaller array will be extended to match the shape of the bigger one. The advantage is that this is done in C under the hood (like any vectorized operations in Numpy). Actually, we used broadcasting in the example 5. The scalar was converted in an array of same shape as $A$.

Here is another generic example:

$$ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix} $$

is equivalent to

$$ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix} $$

where the ($3\times 1$
) matrix is converted to the right shape ($3\times 2$
) by copying the first column. Numpy will do that automatically if the shapes can match.

## Example 6

### Add two matrices of different shapes

In [25]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
B = np.array([[2], [4], [6]])
# B = np.array([2, 4, 6])
B

array([[2],
       [4],
       [6]])

In [29]:
B.shape

(3, 1)

In [30]:
# Broadcasting
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

*Coding tip*: Sometimes row or column vectors are not in proper shape for broadcasting. We need to imploy a trick ( a `numpy.newaxis` object) to help fix this issue.

In [19]:
x = np.arange(4)
x.shape

(4,)

In [20]:
x

array([0, 1, 2, 3])

In [22]:
# Adds a new dimension
x[:, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

In [30]:
np.random.rand(2,3,2)

array([[[0.65121975, 0.36626068],
        [0.65932186, 0.70470253],
        [0.98814632, 0.85030966]],

       [[0.04726903, 0.41919405],
        [0.74752407, 0.56951937],
        [0.69528546, 0.81425237]]])

In [34]:
A = np.random.randn(4,3)
A

array([[-0.40961415,  0.6166584 ,  1.28456147],
       [-0.42494688, -0.43492951,  0.31102454],
       [-1.24008805,  1.73578149, -1.33943425],
       [-1.2965525 ,  0.49557645,  2.02150145]])

In [21]:
# This will throw an error
try:
    A - x
except ValueError:
    print("Operation cannot be completed. Dimension mismatch") 

Operation cannot be completed. Dimension mismatch


In [26]:
# But this works -- subtract each column of A by the column vector x
A - x[:, np.newaxis]

array([[ 0.37898843,  0.42689999, -1.34790859],
       [ 0.59115004, -0.40399615, -0.74489962],
       [-0.91340826, -3.6311077 , -2.78809825],
       [-1.65574227, -2.92895949, -2.93240511]])